{% set name = "ctao-dpps-cosmic-ray-spectra" %}
{% set version = "0.1.1" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ctao_dpps_cosmic_ray_spectra-{{ version }}.tar.gz
  sha256: e051b1f28f8bbac1b771b263ba64a4599142e5129ea2de9c17c377d3f1c72ef2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=65
    - setuptools-scm >=8
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - astropy-base
    - scipy

test:
  imports:
    - ctao_cr_spectra
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://gitlab.cta-observatory.org/cta-computing/dpps/cosmic-ray-spectra
  summary: Common definitions of cosmic ray reference spectra
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - maxnoe
    - GernotMaier
    - orelgueta
